version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    ports:
      - 80:80
    environment:
      YOURLS_DB_PASS: p2463328
      YOURLS_SITE: http://pper.men
      YOURLS_USER: akundev
      YOURLS_PASS: p2463328

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p2463328
